version: "3"

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress # Indique  de ne pas lancer NGINX avant WP
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443" # port expose a la machine locale
    restart: on-failure #redemarre en cas de crash

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on: #WordPress demarrera uniquement apres MariaDB pour pouvoir configurer la bas de donnees
    - mariadb
    restart: on failure 
    expose:
    - "9000"

volumes:
  wordpress:
    driver: local # Stockage du volume en local
    driver_opts:
      type: 'none' # Pas de type specifique
      o: 'bind' # 
      device: '/home/clbernar/data/wordpress' # L'endroit ou stocker sur la machine hote
  mariadb:
   driver: local
   driver_opts:
    type: 'none'
    o: 'bind'
    device: '/home/clbernar/data/mariadb'

networks:
  inception:
    driver: bridge
